CREATE TABLE STUDENT(
	studentID INT Primary Key NOT NULL,
	Name NVARCHAR(50),
	Gender BIT,
	Age INT
)
CREATE TABLE COURSE(
	subjectID INT Primary Key NOT NULL,
	Name NVARCHAR(50),
	Credits INT,
	Price BIGINT
)
CREATE TABLE STUDENTDETAILS(
	studentID INT FOREIGN KEY REFERENCES STUDENT(studentID),
	City NVARCHAR(50),
	Province NVARCHAR(50),
	timeStart DATE,
	trainingProgram BIT
)
CREATE TABLE LEARNINGRESULT(
	studentID INT FOREIGN KEY REFERENCES STUDENT(studentID),
	subjectID INT FOREIGN KEY REFERENCES COURSE(subjectID),
	Grade FLOAT,
	Ability NVARCHAR(10)
)


